version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book-hive-api
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    command: bash -c "composer install && apache2-foreground"
    networks:
      - app-network
    env_file:
      .env
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    container_name: book-hive-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: ${CACHE_NAME}
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
