name: PHPUnit Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      
      - name: List files
        run: ls -la
     
      - name: Install dependencies
        run: composer install

      # - name: Run PHPUnit tests with coverage
      #   run: vendor/bin/phpunit --coverage-clover=coverage.xml

  upload-coverage:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Check coverage file
        run: |
          if [ -f coverage.xml ]; then
            echo "Coverage file found."
          else
            echo "Coverage file not found."
          fi
          
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml