name: PHPUnit Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
     
      - name: Install dependencies
        run: composer install

      - name: Create coverage directory
        run: mkdir -p coverage
  
      - name: Copy coverage report
        run: |
          if [ -f coverage.xml ]; then
            cp coverage.xml coverage/
          else
            echo "Coverage file not found."
            exit 1
          fi
  
      - name: Check coverage file
        run: |
          if [ -f coverage/coverage.xml ]; then
            echo "Coverage file found."
          else
            echo "Coverage file not found."
            exit 1
          fi

  upload-coverage:
    runs-on: ubuntu-latest

    needs: build

    steps:
          
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/coverage.xml